# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-TypingEffort
version:      0.20
version_from: lib/Text/TypingEffort.pm
installdirs:  site
requires:
    Test::More:                    0.31

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
