---
name: Text-TypingEffort
version: 0.21
author:
  - Michael Hendricks <michael@palmcluster.org>
abstract: calculate the effort required to type a given text
license: perl
build_requires:
  Test::More: 0.31
provides:
  Text::TypingEffort:
    file: lib/Text/TypingEffort.pm
    version: 0.21
generated_by: Module::Build version 0.23
