# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-TypingEffort
version:      0.25
version_from: lib/Text/TypingEffort.pm
installdirs:  site
requires:
    File::Temp:                    0.14
    Test::More:                    0.31

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
